version: '3.8'
services:
  db:
    env_file: ./.env
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
    ports:
      - '5433:${DB_PORT}'
    
  server:
    depends_on:
      - db
    env_file: ./.env
    restart: always
    build: ./server
    ports:
      - '9090:${SERVER_PORT}'

  client:
    build: ./client
    env_file: ./.env
    ports:
      - '3000:${CLIENT_PORT}'
    volumes:
      - './client/:/app'
      - '/client/app/node_modules'
    stdin_open: true
    tty: true
    
volumes:
  pgdata: