version: '3.8'
services:
  db:
    env_file: ./.env
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    
  web:
    depends_on:
      - db
    env_file: ./.env
    restart: always
    build: .
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    
volumes:
  pgdata: