version: '3.8'
services:
  db:
    env_file: ./.env
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
    ports:
      - '5433:${DB_PORT}'
    
  web:
    depends_on:
      - db
    env_file: ./.env
    restart: always
    build: .
    ports:
      - '9090:${SERVER_PORT}'
    
volumes:
  pgdata: